version: "2"
plugins:
  fixme:
    enabled: true
  git-legal:
    enabled: true
  gofmt:
    enabled: true
  golint:
    enabled: true
  markdownlint:
    enabled: true
    exclude_patterns:
      - "docs/cli/*.md"
  shellcheck:
    enabled: true
