image: golang:1.12.4

stages:
  - validate
  - release
  - www

validate:
  stage: validate
  services:
    - vault:1.1.1
  variables:
    SKIP_SETCAP: "true"                     # Used in `vault` service
    VAULT_DEV_ROOT_TOKEN_ID: hunter2        # Used in `vault` service
    VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8300  # Used in `vault` service
    VAKU_VAULT_ADDR: http://vault:8300
  script:
    - test -z $(gofmt -l -w -s vaku/) # Make sure no formatting is needed
    - go test -cover -race -v ./...   # Run tests

release:
  stage: release
  only:
    - tags
  except:
    - branches
  script:
    - curl -sL https://git.io/goreleaser | bash

www:
  image: python:3-alpine
  stage: www
  only:
    refs:
      - master
    changes:
      - www/*
  script:
    - pip install awscli
    - aws --region "${S3_REGION}" s3 sync . "s3://${S3_BUCKET_NAME}" --sse AES256
    - aws cloudfront create-invalidation --distribution-id "${CF_DISTRIBUTION_ID}" --paths "/*"
