version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errorlint
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - mnd
    - nakedret
    - nestif
    - prealloc
    - rowserrcheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - wrapcheck

  settings:
    dupl:
      threshold: 100
    errcheck:
      check-blank: true
    gocognit:
      min-complexity: 15
    goconst:
      min-occurrences: 3
    gocyclo:
      min-complexity: 10
    nakedret:
      max-func-lines: 0

  exclusions:
    rules:
      - linters:
          - gochecknoglobals
        path: main.go
      - linters:
          - dupl
          - wrapcheck
        path: cmd/
      - linters:
          - dupl
          - funlen
          - gochecknoglobals
          - gocognit
          - goconst
          - mnd
          - wrapcheck
        path: _test.go
      - linters:
          - errcheck
          - ineffassign
        path: example_*_test.go
      - linters:
          - errcheck
        text: "Error return value of `fmt.Fprintf` is not checked"

formatters:
  enable:
    - gofmt
    - goimports
