project_name: vaku
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: vaku
    binary: vaku
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
archives:
  - id: vaku
    format: zip
    replacements:
      386: i386
      amd64: x86_64
      darwin: mac
      linux: linux
      windows: windows
brews:
  - name: vaku
    description: CLI that extends the official Vault client.
    homepage: https://vaku.dev/
    skip_upload: auto
    github:
      owner: lingrino
      name: homebrew-tap
    folder: Formula
    commit_author:
      name: Sean Lingren
      email: sean@lingrino.com
    test: |
      system "#{bin}/vaku version"
scoop:
  bucket:
    owner: lingrino
    name: scoop-vaku
  description: CLI that extends the official Vault client.
  homepage: https://vaku.dev/
  license: MIT
  commit_author:
    name: Sean Lingren
    email: sean@lingrino.com
nfpms:
  - id: vaku
    description: CLI that extends the official Vault client.
    homepage: https://vaku.dev/
    maintainer: "Sean Lingren <sean@lingrino.com>"
    license: MIT
    formats:
      - deb
      - rpm
    replacements:
      386: i386
      amd64: x86_64
      darwin: mac
      linux: linux
      windows: windows
dockers:
  - dockerfile: Dockerfile
    image_templates:
      - lingrino/vaku:latest
      - lingrino/vaku:{{ .Version }}
      - lingrino/vaku:{{ .Major }}
      - lingrino/vaku:{{ .Major }}.{{ .Minor }}
