project_name: vaku
env:
  - CGO_ENABLED=0
  - GO111MODULE=on
before:
  hooks:
    - go mod download
archives:
  - id: vaku
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
brews:
  - name: vaku
    description: "A CLI and Go API to extend the official Vault client"
    homepage: https://vaku.io/
    skip_upload: auto
    github:
      owner: lingrino
      name: homebrew-tap
    commit_author:
      name: Sean Lingren
      email: sean@lingrino.com
    folder: Formula
    dependencies:
      - vault
    test: |
      system "#{bin}/vaku version"
