changelog:
  sort: asc
  filters:
    exclude:
    - Merge pull request
    - Merge branch
git:
  short_hash: true
builds:
  - binary: vaku
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
brew:
  name: vaku
  github:
    owner: lingrino
    name: homebrew-tap
  commit_author:
    name: lingrino
    email: srlingren@gmail.com
  folder: Formula
  homepage: "https://vaku.io"
  description: "A CLI and Go API to extend the official Vault client"
  skip_upload: true
  dependencies:
    - vault
  build_dependencies:
    - make
    - gcc
