version: 2

project_name: vaku
before:
  hooks:
    - go mod download
builds:
  - id: vaku
    binary: vaku
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
archives:
  - id: vaku
    format: zip
brews:
  - name: vaku
    description: CLI that extends the official Vault client.
    homepage: https://vaku.dev/
    skip_upload: auto
    repository:
      owner: lingrino
      name: homebrew-tap
    directory: Formula
    commit_author:
      name: Sean Lingren
      email: sean@lingren.com
    test: |
      system "#{bin}/vaku version"
nfpms:
  - id: vaku
    description: CLI that extends the official Vault client.
    homepage: https://vaku.dev/
    maintainer: "Sean Lingren <sean@lingren.com>"
    license: MIT
    formats:
      - deb
      - rpm
dockers:
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/lingrino/vaku:latest
      - ghcr.io/lingrino/vaku:{{ .Version }}
      - ghcr.io/lingrino/vaku:{{ .Major }}
      - ghcr.io/lingrino/vaku:{{ .Major }}.{{ .Minor }}
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.version={{.Version}}
