version: 2

project_name: vaku
before:
  hooks:
    - go mod download
builds:
  - id: vaku
    binary: vaku
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
    env:
      - CGO_ENABLED=0
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
archives:
  - id: vaku
    formats: ["zip"]
homebrew_casks:
  - name: vaku
    description: CLI that extends the official Vault client.
    homepage: https://vaku.dev/
    skip_upload: auto
    repository:
      owner: lingrino
      name: homebrew-tap
    directory: Casks
    commit_author:
      name: Sean Lingren
      email: sean@lingren.com
nfpms:
  - id: vaku
    description: CLI that extends the official Vault client.
    homepage: https://vaku.dev/
    maintainer: "Sean Lingren <sean@lingren.com>"
    license: MIT
    formats:
      - deb
      - rpm
dockers_v2:
  - images:
      - ghcr.io/lingrino/vaku
    tags:
      - latest
      - "{{ .Version }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
    labels:
      "--label=org.opencontainers.image.created": "{{.Date}}"
      "--label=org.opencontainers.image.revision": "{{.FullCommit}}"
      "--label=org.opencontainers.image.version": "{{.Version}}"
