changelog:
  sort: asc
  filters:
    exclude:
    - Merge pull request
    - Merge branch
git:
  short_hash: true
builds:
  - binary: vaku
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# brew:
#   name: vaku
#   homepage: "https://vaku.io"
#   description: "A CLI and Go API to extend the official Vault client"
#   skip_upload: true
#   github:
#     owner: lingrino
#     name: homebrew-vaku
#   commit_author:
#     name: lingrino
#     email: srlingren@gmail.com
#   dependencies:
#     - vault
#   build_dependencies:
#     - make
#     - gcc
