name: Validate

on:
  workflow_dispatch:
  push:

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31 # https://github.com/golangci/golangci-lint/releases
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15 # https://golang.org/dl/
      - name: Cache Modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Goreleaser Check
        uses: goreleaser/goreleaser-action@v2
        with:
          args: check
      - name: Docs Check
        run: |
          before=$(cat docs/cli/*.md | md5sum)
          go run main.go docs docs/cli
          after=$(cat docs/cli/*.md | md5sum)
          if [ "$before" != "$after" ]; then exit 1; fi
        shell: bash
      - name: Go Mod Tidy
        run: test -z $(go mod tidy)
      - name: Go Format
        run: test -z $(gofmt -l -s .)
      - name: Test
        run: go test -cover -coverprofile=c.out -covermode=atomic -race -v ./...
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./c.out
          fail_ci_if_error: true
