name: Validate

on:
  - push

jobs:
  validate:
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    steps:
      - name: Code - Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Docs Check
        run: |
          before=$(cat docs/cli/*.md | md5sum)
          go run docs/cli/generate.go
          after=$(cat docs/cli/*.md | md5sum)
          if [ "$before" != "$after" ]; then exit 1; fi
        shell: bash
      - name: Goreleaser Check
        run: goreleaser check
      - name: Go fmt
        run: test -z $(gofmt -l -w -s vaku/)
      - name: Prep Coverage
        run: |
          cc-test-reporter before-build
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Run Tests
        run: go test -cover -coverprofile=c.out -covermode=atomic -race -v ./...
      - name: Upload Coverage
        run: |
          cc-test-reporter after-build -p "github.com/${GITHUB_REPOSITORY}"
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
